# ?????
server:
  port: 80
  servlet:
    context-path: /app #设置应用名

notification:
  service: sms

mycar:
  brand: BYD
  price: 10000

resources:
  static-locations: [classpath:/resources/]

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_test?serverTimezone=Asia/Tokyo
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
